import {firebaseConfig} from './firebase-config.js';
import {NOTES,findChords} from './chords.js?v=8';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const selectedNotes=new Set();let audio;
function play(notes){audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();notes.forEach((p,i)=>{const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.value=261.63*Math.pow(2,p/12);g.gain.setValueAtTime(.0001,audio.currentTime);g.gain.exponentialRampToValueAtTime(.08,audio.currentTime+.04);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+1.1);o.connect(g).connect(audio.destination);o.start(audio.currentTime+i*.035);o.stop(audio.currentTime+1.12)})}
function drawChords(){ $('notes').replaceChildren(...NOTES.map((n,i)=>{const b=document.createElement('button');b.textContent=n;b.className=(selectedNotes.has(i)?'active ':'')+([1,3,6,8,10].includes(i)?'black-key':'white-key');const positions={0:0,2:1,4:2,5:3,7:4,9:5,11:6,1:.72,3:1.72,6:3.72,8:4.72,10:5.72};b.style.setProperty('--key-x',positions[i]);b.setAttribute('aria-pressed',String(selectedNotes.has(i)));b.onclick=()=>{selectedNotes.has(i)?selectedNotes.delete(i):selectedNotes.add(i);drawChords()};return b}));const filter=$('chordFilter').value;let found=findChords([...selectedNotes]);if(filter==='core')found=found.filter(x=>x.coreCount===selectedNotes.size);if(filter==='tension')found=found.filter(x=>x.coreCount<selectedNotes.size);$('resultTitle').textContent=selectedNotes.size?`${found.length}개 코드 후보 · ${[...selectedNotes].sort((a,b)=>a-b).map(x=>NOTES[x]).join(' · ')}`:'음을 선택하세요';$('chordEmpty').hidden=selectedNotes.size>0;const list=$('chords');list.replaceChildren(...found.map(c=>{const b=document.createElement('button');b.className='chord';const title=document.createElement('strong');title.textContent=c.name;const parts=document.createElement('small');parts.textContent=`기본음 ${c.intervals.map(x=>NOTES[(c.root+x)%12]).join(' · ')}`;b.append(title,parts);for(const role of c.roles){const line=document.createElement('small');line.className=role.core?'core':'tension';line.textContent=`${NOTES[role.note]} = ${role.role}`;b.append(line)}b.title='코드 소리 듣기';b.onclick=()=>play([...new Set([...c.intervals.map(x=>c.root+x),...c.roles.filter(x=>!x.core).map(x=>c.root+(x.note-c.root+12)%12)])]);return b}));if(selectedNotes.size&&!found.length){const p=document.createElement('p');p.textContent='현재 지원하는 코드와 텐션 규칙에서 일치하는 후보가 없습니다.';list.append(p)}}
$('clearNotes').onclick=()=>{selectedNotes.clear();drawChords()};$('chordFilter').onchange=drawChords;drawChords();
$('menuBtn').onclick=()=>{const open=$('nav').classList.toggle('open');$('menuBtn').setAttribute('aria-expanded',String(open))};document.querySelectorAll('#nav a').forEach(a=>a.onclick=()=>{$('nav').classList.remove('open');$('menuBtn').setAttribute('aria-expanded','false')});

$('chordExample').onclick=()=>{selectedNotes.clear();selectedNotes.add(0);selectedNotes.add(4);drawChords()};
const navLinks=[...document.querySelectorAll('#nav a')];
if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){navLinks.forEach(a=>a.classList.toggle('active',a.hash==='#'+e.target.id))}},{rootMargin:'-10% 0px -65% 0px'});document.querySelectorAll('#home,.section').forEach(s=>observer.observe(s))}
let db,storage,auth,F,S,A,materials=[],user=null;
function safeUrl(url){try{const u=new URL(url);return ['https:','http:'].includes(u.protocol)?u.href:null}catch{return null}}
function drawMaterials(){ $('materialEmpty').hidden=materials.length>0; $('materialList').replaceChildren(...materials.map(m=>{const article=document.createElement('article');article.className='card material';article.innerHTML=`<span class="kind">${m.type==='video'?'영상':'파일'}</span><h3>${esc(m.title)}</h3><p>${esc(m.description)}</p>`;const a=document.createElement('a');a.textContent=m.type==='video'?'영상 보기':'다운로드';a.target='_blank';a.rel='noopener noreferrer';if(m.type==='video'){a.href=safeUrl(m.url)||'#'}else{a.href='#';a.onclick=async e=>{e.preventDefault();try{const u=await S.getDownloadURL(S.ref(storage,m.path));window.open(u,'_blank','noopener')}catch{alert('파일을 열 수 없습니다.')}}}article.append(a);return article}));$('manageMaterials').replaceChildren(...materials.map(m=>{const row=document.createElement('div');row.className='manage-row';const name=document.createElement('span');name.textContent=m.title;const del=document.createElement('button');del.textContent='삭제';del.onclick=()=>deleteMaterial(m);row.append(name,del);return row}))}
async function deleteMaterial(m){if(!confirm('공개 자료를 삭제할까요?'))return;try{await F.deleteDoc(F.doc(db,'materials',m.id));if(m.path)await S.deleteObject(S.ref(storage,m.path)).catch(()=>{})}catch(e){alert('삭제하지 못했습니다: '+e.message)}}
function showAdmin(){const yes=!!user;$('loginPanel').hidden=yes;$('adminPanel').hidden=!yes;$('adminEmail').textContent=user?.email||''}
function renderShare(data){$('publicSite').hidden=true;$('studentView').hidden=false;$('shareHeading').textContent=`${data.name} · ${data.course||'수업 기록'}`;$('shareLessons').replaceChildren(...(data.lessons||[]).map(l=>{const el=document.createElement('article');el.className='card shared-card';el.innerHTML=`<h2>${esc(l.week)}주차 · ${esc(l.date)}</h2><p>${esc(l.content)}</p><p><strong>다음 시간·과제</strong><br>${esc(l.homework||'없음')}</p>`;return el}));if(!data.lessons?.length)$('shareLessons').textContent='아직 등록된 수업 기록이 없습니다.'}

if(!firebaseConfig){$('setupNotice').hidden=false;$('loginForm').querySelector('button').disabled=true}else{try{
const base='https://www.gstatic.com/firebasejs/10.14.1/';
const [app,fire,store,authentication]=await Promise.all([import(base+'firebase-app.js'),import(base+'firebase-firestore.js'),import(base+'firebase-storage.js'),import(base+'firebase-auth.js')]);
F=fire;S=store;A=authentication;const instance=app.initializeApp(firebaseConfig);db=F.getFirestore(instance);storage=S.getStorage(instance);auth=A.getAuth(instance);
const shareToken=new URLSearchParams(location.search).get('student');
if(shareToken){$('publicSite').hidden=true;$('studentView').hidden=false;try{const record=await F.getDoc(F.doc(db,'studentViews',shareToken));if(record.exists())renderShare(record.data());else $('shareLessons').textContent='유효하지 않거나 만료된 링크입니다.'}catch{$('shareLessons').textContent='수업 기록을 불러올 수 없습니다.'}}
else{
F.onSnapshot(F.query(F.collection(db,'materials'),F.orderBy('createdAt','desc')),snapshot=>{materials=snapshot.docs.map(x=>({id:x.id,...x.data()}));drawMaterials()},error=>{$('materialEmpty').textContent='자료를 불러오지 못했습니다.';console.error(error)});
A.onAuthStateChanged(auth,u=>{user=u;if(u&&!u.emailVerified){A.sendEmailVerification(u).then(()=>alert('인증 이메일을 보냈습니다. 인증 후 다시 로그인해 주세요.')).catch(()=>{});A.signOut(auth);return}showAdmin()});
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginMessage').textContent='로그인 중...';try{await A.signInWithEmailAndPassword(auth,$('email').value,$('password').value);$('loginMessage').textContent='';$('password').value=''}catch{$('loginMessage').textContent='로그인에 실패했습니다. 계정을 확인해 주세요.'}};
$('logoutBtn').onclick=()=>A.signOut(auth);
$('materialForm').onsubmit=async e=>{e.preventDefault();const msg=$('uploadMessage');msg.textContent='게시 중...';const type=$('materialType').value,file=$('materialFile').files[0];if(type==='file'&&!file){msg.textContent='파일을 선택해 주세요.';return}if(file&&file.size>25*1024*1024){msg.textContent='파일은 25MB 이하로 올려 주세요.';return}let path='';try{if(type==='file'){path=`public/${crypto.randomUUID()}/${file.name}`;await S.uploadBytes(S.ref(storage,path),file)}await F.addDoc(F.collection(db,'materials'),{title:$('materialTitle').value.trim(),description:$('materialDescription').value.trim(),type,url:type==='video'?$('materialUrl').value.trim():'',path,createdAt:Date.now()});$('materialForm').reset();$('fileField').hidden=true;$('urlField').hidden=false;msg.textContent='자료가 게시되었습니다.'}catch(err){msg.textContent='게시하지 못했습니다: '+err.message;if(path)await S.deleteObject(S.ref(storage,path)).catch(()=>{})}};
}}
catch(err){$('setupNotice').hidden=false;$('setupNotice').textContent='Firebase 연결에 실패했습니다. 설정과 인터넷 연결을 확인해 주세요.';console.error(err)}}
$('materialType').onchange=()=>{const file=$('materialType').value==='file';$('fileField').hidden=!file;$('urlField').hidden=file};
