import { firebaseConfig } from './firebase-config.js';
const $ = id => document.getElementById(id);
const NOTES=['C','C♯','D','E♭','E','F','F♯','G','A♭','A','B♭','B'];
const CHORDS=[['maj',[0,4,7],'메이저'],['m',[0,3,7],'마이너'],['dim',[0,3,6],'디미니시드'],['aug',[0,4,8],'어그먼티드'],['7',[0,4,7,10],'도미넌트 7'],['maj7',[0,4,7,11],'메이저 7'],['m7',[0,3,7,10],'마이너 7'],['m7♭5',[0,3,6,10],'하프 디미니시드']];
let chosen=0,audio;
function play(pitches){audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();pitches.forEach((p,i)=>{const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.value=261.63*Math.pow(2,p/12);g.gain.setValueAtTime(.0001,audio.currentTime);g.gain.exponentialRampToValueAtTime(.09,audio.currentTime+.04);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+1.1);o.connect(g).connect(audio.destination);o.start(audio.currentTime+i*.035);o.stop(audio.currentTime+1.12)})}
function drawChords(){ $('notes').replaceChildren(...NOTES.map((n,i)=>{const b=document.createElement('button');b.textContent=n;b.className=i===chosen?'active':'';b.setAttribute('aria-pressed',i===chosen);b.onclick=()=>{chosen=i;drawChords()};return b}));$('resultTitle').textContent=`${NOTES[chosen]}를 포함하는 코드`;const cards=[];for(let root=0;root<12;root++)for(const [suffix,intervals,kind] of CHORDS){const n=intervals.indexOf((chosen-root+12)%12);if(n<0)continue;const b=document.createElement('button');b.className='chord';const s=document.createElement('strong');s.textContent=NOTES[root]+suffix;const detail=document.createElement('small');detail.textContent=`${kind} · 선택한 음은 ${n+1}번째 구성음`;b.append(s,detail);b.onclick=()=>play(intervals.map(x=>root+x));cards.push(b)}$('chords').replaceChildren(...cards)}drawChords();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let db,storage,auth,F,S,A,students=[],lessons=[],materials=[],selected=null,user=null;
function safeUrl(url){try{const u=new URL(url);return ['https:','http:'].includes(u.protocol)?u.href:null}catch{return null}}
function drawMaterials(){const list=$('materialList');list.replaceChildren();for(const m of materials){const href=m.type==='video'?safeUrl(m.url):null;const article=document.createElement('article');article.className='card material';article.innerHTML=`<span class="kind">${m.type==='video'?'영상':'파일'}</span><h3>${esc(m.title)}</h3><p>${esc(m.description)}</p>`;const a=document.createElement('a');a.textContent=m.type==='video'?'영상 보기':'다운로드';a.href=href||'#';a.target='_blank';a.rel='noopener noreferrer';if(m.type==='file')a.onclick=async e=>{e.preventDefault();try{const u=await S.getDownloadURL(S.ref(storage,m.path));window.open(u,'_blank','noopener')}catch{alert('파일을 열 수 없습니다. 잠시 후 다시 시도해 주세요.')}};if(m.type==='video'&&!href)a.removeAttribute('href');article.append(a);list.append(article)}$('manageMaterials').replaceChildren(...materials.map(m=>{const row=document.createElement('div');row.className='manage-row';const name=document.createElement('span');name.textContent=m.title;const del=document.createElement('button');del.textContent='삭제';del.onclick=()=>deleteMaterial(m);row.append(name,del);return row}))}
function drawStudents(){ $('studentList').replaceChildren(...students.map(s=>{const b=document.createElement('button');b.className='student-row'+(s.id===selected?' selected':'');b.textContent=s.name;b.onclick=()=>{selected=s.id;drawStudents();drawDetail()};return b}));drawDetail()}
function drawDetail(){const s=students.find(x=>x.id===selected);$('studentEmpty').hidden=!!s;$('studentDetail').hidden=!s;if(!s)return;$('selectedName').textContent=s.name;$('course').value=s.course||'';$('dueDate').value=s.dueDate||'';$('payment').value=s.payment||'예정';$('lessonList').replaceChildren(...lessons.filter(x=>x.studentId===selected).sort((a,b)=>b.date.localeCompare(a.date)).map(l=>{const el=document.createElement('div');el.className='lesson';el.innerHTML=`<strong>${esc(l.week)}주차 · ${esc(l.date)}</strong><p>${esc(l.content)}</p><small>다음 시간·과제: ${esc(l.homework||'없음')}</small>`;const del=document.createElement('button');del.textContent='기록 삭제';del.style.marginLeft='12px';del.onclick=async()=>{if(confirm('이 수업 기록을 삭제할까요?'))await F.deleteDoc(F.doc(db,'lessons',l.id))};el.append(del);return el}))}
async function deleteMaterial(m){if(!confirm('공개 자료를 삭제할까요?'))return;try{await F.deleteDoc(F.doc(db,'materials',m.id));if(m.path)await S.deleteObject(S.ref(storage,m.path)).catch(()=>{})}catch(e){alert('삭제하지 못했습니다: '+e.message)}}
function showAdmin(){const yes=!!user;$('loginPanel').hidden=yes;$('adminPanel').hidden=!yes;$('adminEmail').textContent=user?.email||''}
if(!firebaseConfig){$('setupNotice').hidden=false;$('loginForm').querySelector('button').disabled=true;$('loginMessage').textContent='Firebase 연결 후 로그인할 수 있습니다.'}else{try{const base='https://www.gstatic.com/firebasejs/10.14.1/';const [app,fire,store,authentication]=await Promise.all([import(base+'firebase-app.js'),import(base+'firebase-firestore.js'),import(base+'firebase-storage.js'),import(base+'firebase-auth.js')]);F=fire;S=store;A=authentication;const instance=app.initializeApp(firebaseConfig);db=F.getFirestore(instance);storage=S.getStorage(instance);auth=A.getAuth(instance);
F.onSnapshot(F.query(F.collection(db,'materials'),F.orderBy('createdAt','desc')),s=>{materials=s.docs.map(x=>({id:x.id,...x.data()}));drawMaterials()},e=>{$('materialEmpty').textContent='자료를 불러오지 못했습니다.';console.error(e)});
let stopStudents=()=>{},stopLessons=()=>{};A.onAuthStateChanged(auth,u=>{user=u;showAdmin();if(u&&!u.emailVerified){A.sendEmailVerification(u).then(()=>{alert('관리자 이메일로 인증 링크를 보냈습니다. 인증 후 다시 로그인해 주세요.')}).catch(()=>{});A.signOut(auth);return}stopStudents();stopLessons();students=[];lessons=[];selected=null;drawStudents();if(u){stopStudents=F.onSnapshot(F.collection(db,'students'),s=>{students=s.docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>a.name.localeCompare(b.name,'ko'));if(selected&&!students.some(x=>x.id===selected))selected=null;drawStudents()},e=>alert('학생 목록 접근 권한을 확인해 주세요: '+e.message));stopLessons=F.onSnapshot(F.collection(db,'lessons'),s=>{lessons=s.docs.map(x=>({id:x.id,...x.data()}));drawDetail()},e=>alert('수업 기록 접근 권한을 확인해 주세요: '+e.message))}});
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginMessage').textContent='로그인 중...';try{await A.signInWithEmailAndPassword(auth,$('email').value,$('password').value);$('loginMessage').textContent='';$('password').value=''}catch(err){$('loginMessage').textContent='로그인에 실패했습니다. 계정과 비밀번호를 확인해 주세요.'}};
$('logoutBtn').onclick=()=>A.signOut(auth);
$('studentForm').onsubmit=async e=>{e.preventDefault();try{const d=await F.addDoc(F.collection(db,'students'),{name:$('studentName').value.trim(),course:'',dueDate:'',payment:'예정',createdAt:Date.now()});selected=d.id;$('studentName').value=''}catch(err){alert('학생을 추가하지 못했습니다: '+err.message)}};
$('studentMeta').onsubmit=async e=>{e.preventDefault();if(!selected)return;try{await F.updateDoc(F.doc(db,'students',selected),{course:$('course').value,dueDate:$('dueDate').value,payment:$('payment').value})}catch(err){alert('저장하지 못했습니다: '+err.message)}};
$('deleteStudent').onclick=async()=>{if(!selected||!confirm('학생과 해당 수업 기록을 모두 삭제할까요?'))return;try{const batch=F.writeBatch(db);lessons.filter(x=>x.studentId===selected).forEach(l=>batch.delete(F.doc(db,'lessons',l.id)));batch.delete(F.doc(db,'students',selected));await batch.commit()}catch(err){alert('삭제하지 못했습니다: '+err.message)}};
$('lessonForm').onsubmit=async e=>{e.preventDefault();if(!selected)return;try{await F.addDoc(F.collection(db,'lessons'),{studentId:selected,date:$('lessonDate').value,week:Number($('week').value),content:$('lessonContent').value.trim(),homework:$('homework').value.trim(),createdAt:Date.now()});$('lessonForm').reset();$('lessonDate').value=new Date().toLocaleDateString('en-CA')}catch(err){alert('수업 기록을 저장하지 못했습니다: '+err.message)}};
$('materialForm').onsubmit=async e=>{e.preventDefault();const msg=$('uploadMessage');msg.textContent='게시 중...';const type=$('materialType').value,file=$('materialFile').files[0];if(type==='file'&&!file){msg.textContent='파일을 선택해 주세요.';return}if(file&&file.size>25*1024*1024){msg.textContent='파일은 25MB 이하로 올려 주세요. 긴 영상은 링크를 이용하세요.';return}let path='';try{if(type==='file'){path=`public/${crypto.randomUUID()}/${file.name}`;await S.uploadBytes(S.ref(storage,path),file)}await F.addDoc(F.collection(db,'materials'),{title:$('materialTitle').value.trim(),description:$('materialDescription').value.trim(),type,url:type==='video'?$('materialUrl').value.trim():'',path,createdAt:Date.now()});$('materialForm').reset();$('fileField').hidden=false;$('urlField').hidden=true;msg.textContent='자료가 게시되었습니다.'}catch(err){msg.textContent='게시하지 못했습니다: '+err.message;if(path)await S.deleteObject(S.ref(storage,path)).catch(()=>{})}};
}catch(err){$('setupNotice').hidden=false;$('setupNotice').textContent='Firebase 연결에 실패했습니다. 설정값과 인터넷 연결을 확인해 주세요.';console.error(err)}}
$('lessonDate').value=new Date().toLocaleDateString('en-CA');$('materialType').onchange=()=>{const v=$('materialType').value;$('fileField').hidden=v!=='file';$('urlField').hidden=v!=='video'};
