import {firebaseConfig} from './firebase-config.js';
import {NOTES,findChords} from './chords.js?v=3';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const selectedNotes=new Set();let audio;
function play(notes){audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();notes.forEach((p,i)=>{const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.value=261.63*Math.pow(2,p/12);g.gain.setValueAtTime(.0001,audio.currentTime);g.gain.exponentialRampToValueAtTime(.08,audio.currentTime+.04);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+1.1);o.connect(g).connect(audio.destination);o.start(audio.currentTime+i*.035);o.stop(audio.currentTime+1.12)})}
function drawChords(){ $('notes').replaceChildren(...NOTES.map((n,i)=>{const b=document.createElement('button');b.textContent=n;b.className=selectedNotes.has(i)?'active':'';b.setAttribute('aria-pressed',String(selectedNotes.has(i)));b.onclick=()=>{selectedNotes.has(i)?selectedNotes.delete(i):selectedNotes.add(i);drawChords()};return b}));const filter=$('chordFilter').value;let found=findChords([...selectedNotes]);if(filter==='core')found=found.filter(x=>x.coreCount===selectedNotes.size);if(filter==='tension')found=found.filter(x=>x.coreCount<selectedNotes.size);$('resultTitle').textContent=selectedNotes.size?`${found.length}개 코드 후보 · ${[...selectedNotes].sort((a,b)=>a-b).map(x=>NOTES[x]).join(' · ')}`:'음을 선택하세요';const list=$('chords');list.replaceChildren(...found.map(c=>{const b=document.createElement('button');b.className='chord';const title=document.createElement('strong');title.textContent=c.name;const parts=document.createElement('small');parts.textContent=`기본음 ${c.intervals.map(x=>NOTES[(c.root+x)%12]).join(' · ')}`;b.append(title,parts);for(const role of c.roles){const line=document.createElement('small');line.className=role.core?'core':'tension';line.textContent=`${NOTES[role.note]} = ${role.role}`;b.append(line)}b.title='코드 소리 듣기';b.onclick=()=>play([...new Set([...c.intervals.map(x=>c.root+x),...c.roles.filter(x=>!x.core).map(x=>c.root+(x.note-c.root+12)%12)])]);return b}));if(selectedNotes.size&&!found.length){const p=document.createElement('p');p.textContent='현재 지원하는 코드와 텐션 규칙에서 일치하는 후보가 없습니다.';list.append(p)}}
$('clearNotes').onclick=()=>{selectedNotes.clear();drawChords()};$('chordFilter').onchange=drawChords;drawChords();
$('menuBtn').onclick=()=>{const open=$('nav').classList.toggle('open');$('menuBtn').setAttribute('aria-expanded',String(open))};document.querySelectorAll('#nav a').forEach(a=>a.onclick=()=>{$('nav').classList.remove('open');$('menuBtn').setAttribute('aria-expanded','false')});
let db,storage,auth,F,S,A,students=[],lessons=[],payments=[],materials=[],selected=null,user=null,month=new Date(),activeDay='',shareToken=new URLSearchParams(location.search).get('student');
const dateToday=()=>new Date().toLocaleDateString('en-CA');$('lessonDate').value=dateToday();$('paidDate').value=dateToday();
function safeUrl(url){try{const u=new URL(url);return ['https:','http:'].includes(u.protocol)?u.href:null}catch{return null}}
function drawMaterials(){ $('materialList').replaceChildren(...materials.map(m=>{const article=document.createElement('article');article.className='card material';article.innerHTML=`<span class="kind">${m.type==='video'?'영상':'파일'}</span><h3>${esc(m.title)}</h3><p>${esc(m.description)}</p>`;const a=document.createElement('a');a.textContent=m.type==='video'?'영상 보기':'다운로드';a.target='_blank';a.rel='noopener noreferrer';if(m.type==='video'){a.href=safeUrl(m.url)||'#'}else{a.href='#';a.onclick=async e=>{e.preventDefault();try{const u=await S.getDownloadURL(S.ref(storage,m.path));window.open(u,'_blank','noopener')}catch{alert('파일을 열 수 없습니다.')}}}article.append(a);return article}));$('manageMaterials').replaceChildren(...materials.map(m=>{const row=document.createElement('div');row.className='manage-row';const name=document.createElement('span');name.textContent=m.title;const del=document.createElement('button');del.textContent='삭제';del.onclick=()=>deleteMaterial(m);row.append(name,del);return row}))}
async function deleteMaterial(m){if(!confirm('공개 자료를 삭제할까요?'))return;try{await F.deleteDoc(F.doc(db,'materials',m.id));if(m.path)await S.deleteObject(S.ref(storage,m.path)).catch(()=>{})}catch(e){alert('삭제하지 못했습니다: '+e.message)}}
function showAdmin(){const yes=!!user;$('loginPanel').hidden=yes;$('adminPanel').hidden=!yes;$('adminEmail').textContent=user?.email||''}
function drawStudents(){ $('studentList').replaceChildren(...students.map(s=>{const b=document.createElement('button');b.className='student-row'+(s.id===selected?' selected':'');b.textContent=s.name;b.onclick=()=>{selected=s.id;drawStudents()};return b}));drawDetail();drawCalendar()}
function studentRecord(s){return {name:s.name,course:s.course||'',lessons:lessons.filter(l=>l.studentId===s.id).map(l=>({date:l.date,week:l.week,content:l.content,homework:l.homework||''})).sort((a,b)=>b.date.localeCompare(a.date)),updatedAt:Date.now()}}
async function updateSharedViews(){if(!user)return;for(const s of students.filter(x=>x.shareToken)){try{await F.setDoc(F.doc(db,'studentViews',s.shareToken),studentRecord(s))}catch(err){console.error('공유 화면 갱신 실패',err)}}}
function drawDetail(){const s=students.find(x=>x.id===selected);$('studentEmpty').hidden=!!s;$('studentDetail').hidden=!s;if(!s)return;$('selectedName').textContent=s.name;$('course').value=s.course||'';$('dueDate').value=s.dueDate||'';$('payment').value=s.payment||'예정';$('shareLink').value=s.shareToken?`${location.origin}${location.pathname}?student=${encodeURIComponent(s.shareToken)}`:'';$('lessonList').replaceChildren(...lessons.filter(l=>l.studentId===selected).sort((a,b)=>b.date.localeCompare(a.date)).map(l=>{const el=document.createElement('div');el.className='record';el.innerHTML=`<strong>${esc(l.week)}주차 · ${esc(l.date)}</strong><p>${esc(l.content)}</p><small>다음 시간·과제: ${esc(l.homework||'없음')}</small>`;const edit=document.createElement('button');edit.textContent='수정';edit.onclick=()=>{$('lessonEditId').value=l.id;$('lessonDate').value=l.date;$('week').value=l.week;$('lessonContent').value=l.content;$('homework').value=l.homework||'';$('lessonSave').textContent='수업 기록 수정';$('cancelEdit').hidden=false;$('lessonForm').scrollIntoView({behavior:'smooth'})};const del=document.createElement('button');del.textContent='삭제';del.onclick=async()=>{if(confirm('이 수업 기록을 삭제할까요?'))await F.deleteDoc(F.doc(db,'lessons',l.id))};el.append(edit,del);return el}));$('paymentList').replaceChildren(...payments.filter(p=>p.studentId===selected).sort((a,b)=>b.date.localeCompare(a.date)).map(p=>{const el=document.createElement('div');el.className='record';const info=document.createElement('strong');info.textContent=`${p.date} 결제 완료${p.amount?' · '+Number(p.amount).toLocaleString()+'원':''}`;const edit=document.createElement('button');edit.textContent='수정';edit.onclick=()=>{$('paymentEditId').value=p.id;$('paidDate').value=p.date;$('amount').value=p.amount||'';$('paymentSave').textContent='결제 기록 수정';$('cancelPaymentEdit').hidden=false;$('paymentForm').scrollIntoView({behavior:'smooth'})};const del=document.createElement('button');del.textContent='삭제';del.onclick=async()=>{if(confirm('이 결제 기록을 삭제할까요?'))await F.deleteDoc(F.doc(db,'payments',p.id))};el.append(info,edit,del);return el}))}
function drawCalendar(){const y=month.getFullYear(),m=month.getMonth();$('calendarTitle').textContent=`${y}년 ${m+1}월`;const start=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate();const events={};const add=(date,type,label)=>{if(!date)return;(events[date]??=[]).push({type,label})};for(const l of lessons)add(l.date,'lesson',`${students.find(s=>s.id===l.studentId)?.name||'학생'} ${l.week}주차`);for(const p of payments)add(p.date,'paid',`${students.find(s=>s.id===p.studentId)?.name||'학생'} 결제`);for(const s of students)if(s.dueDate&&s.payment!=='완료')add(s.dueDate,'due',`${s.name} 예정`);const cells=[];for(const name of ['일','월','화','수','목','금','토']){const t=document.createElement('div');t.className='weekday';t.textContent=name;cells.push(t)}for(let i=0;i<start;i++){const blank=document.createElement('div');blank.className='day blank';cells.push(blank)}for(let d=1;d<=days;d++){const date=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;const b=document.createElement('button');b.className='day'+(date===dateToday()?' today':'')+(date===activeDay?' selected':'');b.textContent=String(d);for(const e of events[date]||[]){const span=document.createElement('span');span.className='event '+e.type;span.textContent=e.label;b.append(span)}b.onclick=()=>{activeDay=date;drawCalendar()};cells.push(b)}$('calendar').replaceChildren(...cells);$('dayDetail').textContent=activeDay?`${activeDay} · ${(events[activeDay]||[]).map(e=>e.label).join(' / ')||'기록 없음'}`:'날짜를 누르면 수업·결제 기록을 볼 수 있어요.'}
$('prevMonth').onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1);activeDay='';drawCalendar()};$('nextMonth').onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1);activeDay='';drawCalendar()};
function renderShare(data){$('publicSite').hidden=true;$('studentView').hidden=false;$('shareHeading').textContent=`${data.name} · ${data.course||'수업 기록'}`;$('shareLessons').replaceChildren(...(data.lessons||[]).map(l=>{const el=document.createElement('article');el.className='card shared-card';el.innerHTML=`<h2>${esc(l.week)}주차 · ${esc(l.date)}</h2><p>${esc(l.content)}</p><p><strong>다음 시간·과제</strong><br>${esc(l.homework||'없음')}</p>`;return el}));if(!data.lessons?.length)$('shareLessons').textContent='아직 등록된 수업 기록이 없습니다.'}
if(!firebaseConfig){$('setupNotice').hidden=false;$('loginForm').querySelector('button').disabled=true}else{try{const base='https://www.gstatic.com/firebasejs/10.14.1/';const [app,fire,store,authentication]=await Promise.all([import(base+'firebase-app.js'),import(base+'firebase-firestore.js'),import(base+'firebase-storage.js'),import(base+'firebase-auth.js')]);F=fire;S=store;A=authentication;const instance=app.initializeApp(firebaseConfig);db=F.getFirestore(instance);storage=S.getStorage(instance);auth=A.getAuth(instance);
if(shareToken){$('publicSite').hidden=true;$('studentView').hidden=false;F.getDoc(F.doc(db,'studentViews',shareToken)).then(s=>{if(s.exists())renderShare(s.data());else $('shareLessons').textContent='유효하지 않거나 만료된 링크입니다.'}).catch(()=>{$('shareLessons').textContent='수업 기록을 불러올 수 없습니다.'})}else{
F.onSnapshot(F.query(F.collection(db,'materials'),F.orderBy('createdAt','desc')),s=>{materials=s.docs.map(x=>({id:x.id,...x.data()}));drawMaterials()},e=>{$('materialEmpty').textContent='자료를 불러오지 못했습니다.';console.error(e)});
let stopStudents=()=>{},stopLessons=()=>{},stopPayments=()=>{};A.onAuthStateChanged(auth,u=>{user=u;showAdmin();if(u&&!u.emailVerified){A.sendEmailVerification(u).then(()=>alert('인증 이메일을 보냈습니다. 인증 후 다시 로그인해 주세요.')).catch(()=>{});A.signOut(auth);return}stopStudents();stopLessons();stopPayments();students=[];lessons=[];payments=[];selected=null;drawStudents();if(u){stopStudents=F.onSnapshot(F.collection(db,'students'),s=>{students=s.docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>a.name.localeCompare(b.name,'ko'));if(selected&&!students.some(x=>x.id===selected))selected=null;drawStudents();updateSharedViews()},e=>alert('학생 목록 접근 권한을 확인해 주세요: '+e.message));stopLessons=F.onSnapshot(F.collection(db,'lessons'),s=>{lessons=s.docs.map(x=>({id:x.id,...x.data()}));drawDetail();drawCalendar();updateSharedViews()},e=>alert('수업 기록 접근 권한을 확인해 주세요: '+e.message));stopPayments=F.onSnapshot(F.collection(db,'payments'),s=>{payments=s.docs.map(x=>({id:x.id,...x.data()}));drawDetail();drawCalendar()},e=>alert('결제 기록 접근 권한을 확인해 주세요: '+e.message))}});
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginMessage').textContent='로그인 중...';try{await A.signInWithEmailAndPassword(auth,$('email').value,$('password').value);$('loginMessage').textContent='';$('password').value=''}catch{$('loginMessage').textContent='로그인에 실패했습니다. 계정을 확인해 주세요.'}};$('logoutBtn').onclick=()=>A.signOut(auth);
$('studentForm').onsubmit=async e=>{e.preventDefault();try{const d=await F.addDoc(F.collection(db,'students'),{name:$('studentName').value.trim(),course:'',dueDate:'',payment:'예정',createdAt:Date.now()});selected=d.id;$('studentName').value=''}catch(err){alert('학생을 추가하지 못했습니다: '+err.message)}};
$('studentMeta').onsubmit=async e=>{e.preventDefault();if(!selected)return;try{await F.updateDoc(F.doc(db,'students',selected),{course:$('course').value,dueDate:$('dueDate').value,payment:$('payment').value})}catch(err){alert('저장하지 못했습니다: '+err.message)}};
$('deleteStudent').onclick=async()=>{const s=students.find(x=>x.id===selected);if(!s||!confirm('학생과 모든 수업·결제 기록을 삭제할까요?'))return;try{const batch=F.writeBatch(db);lessons.filter(x=>x.studentId===selected).forEach(l=>batch.delete(F.doc(db,'lessons',l.id)));payments.filter(x=>x.studentId===selected).forEach(p=>batch.delete(F.doc(db,'payments',p.id)));if(s.shareToken)batch.delete(F.doc(db,'studentViews',s.shareToken));batch.delete(F.doc(db,'students',selected));await batch.commit()}catch(err){alert('삭제하지 못했습니다: '+err.message)}};
$('rotateShare').onclick=async()=>{const s=students.find(x=>x.id===selected);if(!s)return;if(s.shareToken&&!confirm('기존 공유 링크를 폐기하고 새 링크를 만들까요?'))return;try{const token=crypto.randomUUID()+crypto.randomUUID();const batch=F.writeBatch(db);batch.update(F.doc(db,'students',s.id),{shareToken:token});batch.set(F.doc(db,'studentViews',token),studentRecord(s));if(s.shareToken)batch.delete(F.doc(db,'studentViews',s.shareToken));await batch.commit()}catch(err){alert('공유 링크를 만들지 못했습니다: '+err.message)}};$('copyShare').onclick=async()=>{if(!$('shareLink').value)return;await navigator.clipboard.writeText($('shareLink').value);alert('링크를 복사했습니다.')};
function resetPayment(){ $('paymentForm').reset();$('paidDate').value=dateToday();$('paymentEditId').value='';$('paymentSave').textContent='결제 기록 추가';$('cancelPaymentEdit').hidden=true}$('cancelPaymentEdit').onclick=resetPayment; $('paymentForm').onsubmit=async e=>{e.preventDefault();if(!selected)return;try{const data={studentId:selected,date:$('paidDate').value,amount:Number($('amount').value)||0};if($('paymentEditId').value)await F.updateDoc(F.doc(db,'payments',$('paymentEditId').value),data);else await F.addDoc(F.collection(db,'payments'),{...data,createdAt:Date.now()});resetPayment()}catch(err){alert('결제 기록을 저장하지 못했습니다: '+err.message)}};
function resetLesson(){ $('lessonForm').reset();$('lessonDate').value=dateToday();$('lessonEditId').value='';$('lessonSave').textContent='수업 기록 추가';$('cancelEdit').hidden=true}$('cancelEdit').onclick=resetLesson;
$('lessonForm').onsubmit=async e=>{e.preventDefault();if(!selected)return;const data={studentId:selected,date:$('lessonDate').value,week:Number($('week').value),content:$('lessonContent').value.trim(),homework:$('homework').value.trim()};try{if($('lessonEditId').value)await F.updateDoc(F.doc(db,'lessons',$('lessonEditId').value),data);else await F.addDoc(F.collection(db,'lessons'),{...data,createdAt:Date.now()});resetLesson()}catch(err){alert('수업 기록을 저장하지 못했습니다: '+err.message)}};
$('materialForm').onsubmit=async e=>{e.preventDefault();const msg=$('uploadMessage');msg.textContent='게시 중...';const type=$('materialType').value,file=$('materialFile').files[0];if(type==='file'&&!file){msg.textContent='파일을 선택해 주세요.';return}if(file&&file.size>25*1024*1024){msg.textContent='파일은 25MB 이하로 올려 주세요.';return}let path='';try{if(type==='file'){path=`public/${crypto.randomUUID()}/${file.name}`;await S.uploadBytes(S.ref(storage,path),file)}await F.addDoc(F.collection(db,'materials'),{title:$('materialTitle').value.trim(),description:$('materialDescription').value.trim(),type,url:type==='video'?$('materialUrl').value.trim():'',path,createdAt:Date.now()});$('materialForm').reset();$('fileField').hidden=true;$('urlField').hidden=false;msg.textContent='자료가 게시되었습니다.'}catch(err){msg.textContent='게시하지 못했습니다: '+err.message;if(path)await S.deleteObject(S.ref(storage,path)).catch(()=>{})}};
}}
catch(err){$('setupNotice').hidden=false;$('setupNotice').textContent='Firebase 연결에 실패했습니다. 설정과 인터넷 연결을 확인해 주세요.';console.error(err)}}
$('materialType').onchange=()=>{const file=$('materialType').value==='file';$('fileField').hidden=!file;$('urlField').hidden=file};
